using Microsoft.EntityFrameworkCore;
using PermissionAPI.Data;
using PermissionAPI.Models.DTOs;
using PermissionAPI.Models.SpResults;
using PermissionAPI.Services.Interfaces;

namespace PermissionAPI.Services.Implementations;

/// <summary>
/// Implementation of user permission service
/// </summary>
public class UserPermissionService : IUserPermissionService
{
    private readonly AppDbContext _context;
    private readonly ILogger<UserPermissionService> _logger;

    public UserPermissionService(AppDbContext context, ILogger<UserPermissionService> logger)
    {
        _context = context;
        _logger = logger;
    }

    /// <summary>
    /// Gets user permissions using stored procedure (recommended for performance)
    /// </summary>
    public async Task<IReadOnlyList<PermissionDto>> GetUserPermissionsAsync(
        int userId, 
        CancellationToken cancellationToken = default)
    {
        _logger.LogInformation("Fetching permissions for UserId {UserId} using stored procedure", userId);

        var results = await _context.UserPermissionResults
            .FromSqlInterpolated($"EXEC dbo.sp_GetUserPermissions @UserId = {userId}")
            .AsNoTracking() // Performance: no change tracking needed
            .ToListAsync(cancellationToken);

        var permissions = results
            .Select(r => new PermissionDto {
                UserName = r.UserName,
                PermissionKey = r.PermissionKey,
                PermissionName = r.PermissionName,
                GroupName = r.GroupName
            })
            .ToList();

        _logger.LogInformation("Found {Count} permissions for UserId {UserId}", permissions.Count, userId);

        return permissions.AsReadOnly();
    }

    /// <summary>
    /// Gets user permissions using LINQ (alternative to SP)
    /// Logic: UNION of direct permissions + permissions from user's groups
    /// Uses the many-to-many navigation properties generated by EF Core scaffolding
    /// </summary>
    public async Task<IReadOnlyList<PermissionDto>> GetUserPermissionsLinqAsync(
        int userId, 
        CancellationToken cancellationToken = default)
    {
        _logger.LogInformation("Fetching permissions for UserId {UserId} using LINQ", userId);

        // Using the scaffolded navigation properties on User entity
        var user = await _context.Users
            .Where(u => u.UserId == userId)
            .Select(u => new
            {
                // Direct permissions
                DirectPermissions = u.Permissions.Select(p => p.PermissionKey),
                // Group-based permissions
                GroupPermissions = u.Groups.SelectMany(g => g.Permissions).Select(p => p.PermissionKey)
            })
            .AsNoTracking()
            .FirstOrDefaultAsync(cancellationToken);

        if (user == null)
        {
            _logger.LogInformation("No user found with UserId {UserId}", userId);
            return Array.Empty<PermissionDto>();
        }

        // Combine and distinct
        var permissionKeys = user.DirectPermissions
            .Union(user.GroupPermissions)
            .Distinct()
            .OrderBy(key => key)
            .Select(key => new PermissionDto { PermissionKey = key })
            .ToList();

        _logger.LogInformation("Found {Count} permissions for UserId {UserId}", permissionKeys.Count, userId);

        return permissionKeys.AsReadOnly();
    }

    /// <summary>
    /// Checks if user exists (for validation)
    /// </summary>
    public async Task<bool> UserExistsAsync(int userId, CancellationToken cancellationToken = default)
    {
        return await _context.Users
            .AsNoTracking()
            .AnyAsync(u => u.UserId == userId, cancellationToken);
    }
}
